Mobile Styling + Animation
bold-commerce/checkout-sample-projects pull request #25
Opened 2021-11-29 20:00 UTC by TimeBones

[HDLS-177] - Update mobile styling and animations
**Changes**
*All CSS made to match mobile view
*CSS transitions and transformations added
*Moved `IndexPage` and `PaymentMethod` from the OneClickLayout into the CheckoutForm
*`Summary` and `Shipping` moved outside the router
*Card props can now take a function

**Removed**
*@media css parameters for smaller screens
*Unused props from `LineItems`

2021-11-30 15:42 UTC, kfalkowski11 approved these changes

2021-11-30 17:45 UTC, arvinder-bold approved these changes

2021-12-01 14:43 UTC, CalinR requested changes

2021-12-01 14:43 UTC, CalinR commented on one_click/client/components/OneClickLayout/components/Card/Card.jsx
>            <span onClick={() => setOpenModal(s => !s) }>{title}</span>
I know this wasn't a change you added in this commit, but it seems like clicking the "Payment" heading would close the modal? I don't think clicking the payment heading should actually do anything based on how we've modified the design.

2021-12-01 15:06 UTC, CalinR approved these changes

2021-12-01 17:26 UTC, closed without merging