Guest flow index page
bold-commerce/checkout-sample-projects pull request #36
Opened 2021-12-08 21:39 UTC by TimeBones

[HDLS-200] - Create new checkout flow

**Changes**
* Added guest flow index page
* CheckoutForm now checks for customer id to render index page
* Shipping lines now are inactive unless they are part of the active page
* Shipping lines have disabled prop to pass to radio buttons
* Added chevron right icon

2021-12-08 22:53 UTC, kfalkowski11 approved these changes

2021-12-10 17:11 UTC, CalinR requested changes

2021-12-10 17:11 UTC, CalinR commented on one_click/client/components/OneClickLayout/OneClickLayout.css
> +.IndexGuest-customer,
I think I may have missed this on other merge requests. We use the BEM class naming convention http://getbem.com/naming/

So these class names should be something like IndexGuest__Customer and IndexGuest__ShippingAddress to stay consistent with the rest of the app

2021-12-13 16:04 UTC, CalinR approved these changes

2021-12-14 19:38 UTC, closed without merging