summary component
bold-commerce/checkout-sample-projects pull request #39
Opened 2021-12-09 18:52 UTC by kfalkowski11

#### Overview
* create condensed summary component for guest checkout

2021-12-09 19:06 UTC, TimeBones commented on one_click/client/components/OneClickLayout/components/Index/IndexGuest.jsx
> -          <ChevronRight className="IndexGuest-chevron"/>
Can remove imports for the chevron and price

2021-12-09 21:04 UTC, TimeBones approved these changes

2021-12-10 17:06 UTC, CalinR requested changes

2021-12-10 17:06 UTC, CalinR commented on one_click/client/components/OneClickLayout/components/Summary/SummaryCondensed.jsx
> +    <div className="IndexGuest-summary">
Not sure if I've missed this on other commits. We use the BEM class naming convention. http://getbem.com/naming/

So for these class names I think we should be using **IndexGuest__Summary** to stay consistent with the rest of the app.

This would be the same for the other class names below

2021-12-13 14:44 UTC, CalinR approved these changes

2021-12-14 15:10 UTC, TimeBones commented on one_click/client/components/OneClickLayout/components/Summary/SummaryCondensed.jsx
> +        onClick={() => onSectionChange('summary')}
Should change passing in onSectionChange without params to passing it with params / general onClick method. Currently it won't work with the billing to summary transition.

2021-12-14 16:34 UTC, TimeBones commented on one_click/client/components/OneClickLayout/components/Index/IndexGuest.jsx
> +      <SummaryCondensed onSectionChange={() => onSectionChange('summaryB')}/>
Should be `onSectionChange('summary')` from the index

2021-12-14 19:44 UTC, closed without merging