Line item variant titles
bold-commerce/checkout-sample-projects pull request #40
Opened 2021-12-10 16:53 UTC by TimeBones

[HDLS-205] - Add Line Item Product Title

**CHANGES**
* useVariant hook added
* line items show variants
* If stock isn't tracked an inventory issue will not be raised

2021-12-10 17:04 UTC, CalinR requested changes

2021-12-10 17:04 UTC, CalinR commented on one_click/server/index.js
> +               tracking:  item.inventory_tracking_service
I think this should also check to see if the variant allows backordering as well. It should be called allow_backorder in the response we get back from the products endpoint

2021-12-10 17:28 UTC, TimeBones commented on one_click/server/index.js
> +               tracking:  item.inventory_tracking_service
Not getting allow_backorder from big commerce response, going to hold off until we can test that.

2021-12-13 17:09 UTC, TimeBones commented on one_click/client/components/OneClickLayout/components/LineItems/LineItems.jsx
> +const handleVariants = useVariants();
Fixed.

2021-12-13 17:10 UTC, TimeBones commented on one_click/client/hooks/useVariants.js
> +const useVariants = () => {
Refactored hook and added map to description in product + inventory item.

2021-12-14 19:38 UTC, closed without merging