Separate frontend
bold-commerce/checkout-sample-projects pull request #51
Opened 2021-12-20 17:32 UTC by TimeBones

[HDLS-211] - Split Single Page Frontend

* Renamed client folder to src
* Server folder removed
* Backend paths changed to .env variables

2021-12-22 17:27 UTC, kfalkowski11 commented on single_page/package.json
> -    "node-fetch": "^2.6.1",
You'll also want to remove the server references in the scripts tag

2022-01-05 15:24 UTC, CalinR requested changes

2022-01-05 15:24 UTC, CalinR commented on single_page/src/layouts/SinglePageLayout/SinglePageLayout.jsx
> +      navigate(`/${process.env.CONFIRMATION_URL}?public_order_id=${state.publicOrderId}`);
We should probably note that this is a relative url somehow in the .env.example. Without that, the developer might assume it's an absolute url.

2022-01-13 19:45 UTC, TimeBones commented on single_page/README.md
> +      "platform_id": "string",
This needs to be updated

2022-01-19 20:31 UTC, closed without merging