One click split frontend
bold-commerce/checkout-sample-projects pull request #53
Opened 2022-01-12 20:57 UTC by kfalkowski11

#### Overview
* Changing the file folder structure to mimic single_page

2022-01-12 21:11 UTC, CalinR requested changes

2022-01-12 21:11 UTC, CalinR commented on single_page/package.json
> +    "express": "^4.17.1",
express, express-handlebars, node-fetch can all be removed since they are all related to the server side of the app

2022-01-12 21:15 UTC, kfalkowski11 commented on single_page/package.json
> +    "express": "^4.17.1",
removed

2022-01-12 21:22 UTC, CalinR approved these changes

2022-01-13 19:13 UTC, TimeBones approved these changes

2022-01-18 14:26 UTC, merged