Resize checkout form on banner mobile
bold-commerce/checkout-sample-projects pull request #66
Opened 2022-01-28 19:46 UTC by TimeBones

[HDLS-235] - Mobile Height incorrect after error
Resizes checkout form on mobile when there are banners. Allows the form to be fully scrollable when there are banners present.

2022-01-31 15:22 UTC, kfalkowski11 approved these changes

2022-02-04 20:50 UTC, CalinR requested changes

2022-02-04 20:50 UTC, CalinR commented on one_click/src/components/CheckoutForm/CheckoutForm.jsx
> +      const checkoutDiv = document.querySelector('[bold-one-click-form]');
I think we should use a useRef instead of a querySelector here

2022-02-08 14:51 UTC, CalinR approved these changes

2022-02-10 14:32 UTC, merged